### ISSUE TITLE
3.0 微服务入门- 3.2-user-service配置文件书写问题

### ISSUE THREAD

**Issue by Luke-Evan** [ForceInjection/cloud-native-dev#1]
user-service源码的application.properties
关于数据库的url书写是否应该加上 `&allowPublicKeyRetrieval=true`

spring.datasource.url=jdbc:mysql://mysql:3306/user?charset=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true

否则似乎会导致无法访问该服务，log显示原因是mysql初始化失败使user-service的pod处于CrashLoopBackOff状态
<img width="1134" alt="微信图片_20240709213340" src="https://github.com/ForceInjection/cloud-native-dev/assets/110676251/8ca6ad29-142e-4817-b1c0-31479fda9134">

该问题在6月7日群聊已有同学提出，我在初次尝试时也遇到了同样的问题
<img width="952" alt="微信图片_20240709212909" src="https://github.com/ForceInjection/cloud-native-dev/assets/110676251/58a874f9-72e1-4580-aa65-3f4e07c9ec71">

通过修改配置文件可以解决

**Comment by grissomsh** [comment]
@Luke-Evan 可否提一个 PR？
